-- =====================================================================
--  Perfume DB - authoritative schema (single source of truth)
--  Run by import_datasets.js at the start of every import.
--  Safe to re-run: everything is dropped and rebuilt from scratch,
--  because 100% of the data is re-derivable from the 3 source files.
-- =====================================================================

BEGIN;

-- Drop in any order thanks to CASCADE
DROP TABLE IF EXISTS perfume_notes    CASCADE;
DROP TABLE IF EXISTS perfume_accords  CASCADE;
DROP TABLE IF EXISTS ingredient_aliases CASCADE;
DROP TABLE IF EXISTS perfumes         CASCADE;
DROP TABLE IF EXISTS accords          CASCADE;
DROP TABLE IF EXISTS ingredients      CASCADE;
DROP TABLE IF EXISTS brands           CASCADE;

-- ---------------------------------------------------------------------
-- brands : deduplicated by a normalized name (cross-source)
-- ---------------------------------------------------------------------
CREATE TABLE brands (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255) NOT NULL,          -- display name (first seen wins)
    name_normalized VARCHAR(255) NOT NULL UNIQUE,   -- dedup key: "W.Dressroom" = "W Dressroom"
    logo_url        TEXT,                           -- filled by scrape_fragrantica_designers.js + import stage 5
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------
-- ingredients : the canonical raw-material / note vocabulary.
-- Rich rows come from Premiere Peau (from_glossary = true), thin rows
-- are created on demand for notes seen only in Fragrantica / Parfumo.
-- image_url is filled later by the ingredient-photo enrichment stage
-- (scrape_fragrantica_notes.js + import stage 4), independent from
-- from_glossary/technical-card enrichment.
-- ---------------------------------------------------------------------
CREATE TABLE ingredients (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                  VARCHAR(255) NOT NULL,          -- canonical display name
    name_normalized       VARCHAR(255) NOT NULL UNIQUE,   -- dedup key
    category              VARCHAR(255),
    subcategory           VARCHAR(255),
    short_description     TEXT,
    botanical_name        VARCHAR(255),
    appearance            TEXT,
    odor_strength         VARCHAR(255),
    producing_countries   TEXT,
    typical_volatility    VARCHAR(255),
    evolution_immediate   TEXT,
    evolution_after_hours TEXT,
    evolution_after_days  TEXT,
    full_extracted_text   TEXT,
    source_url            TEXT,
    image_url             TEXT,
    from_glossary         BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------
-- ingredient_aliases : every surface form ("cedar", "cedarwood",
-- "sicilian bergamot") points to its canonical ingredient, so a
-- search-by-note resolves any spelling to a single ingredient id.
-- ---------------------------------------------------------------------
CREATE TABLE ingredient_aliases (
    alias_normalized VARCHAR(255) PRIMARY KEY,
    ingredient_id    BIGINT NOT NULL REFERENCES ingredients(id) ON DELETE CASCADE
);

-- ---------------------------------------------------------------------
-- accords : dimension table so accords become an id-based search axis,
-- symmetric to brands and ingredients (was a free-text column before).
-- ---------------------------------------------------------------------
CREATE TABLE accords (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(100) NOT NULL,
    name_normalized VARCHAR(100) NOT NULL UNIQUE
);

-- ---------------------------------------------------------------------
-- perfumes : one row per real fragrance, deduplicated across sources
-- by (brand_id, title_normalized). image_url is derived directly from
-- the Fragrantica perfume-page URL (numeric id at the end) - no scraping
-- needed for this one, see extractFragranticaImage() in import_datasets.js.
-- ---------------------------------------------------------------------
CREATE TABLE perfumes (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_id         BIGINT       NOT NULL REFERENCES brands(id) ON DELETE CASCADE,
    title            VARCHAR(255) NOT NULL,
    title_normalized VARCHAR(255) NOT NULL,
    description      TEXT,
    release_year     INTEGER,
    perfumer         VARCHAR(255),
    image_url        TEXT,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    UNIQUE (brand_id, title_normalized)
);

-- ---------------------------------------------------------------------
-- perfume_notes : olfactory pyramid (junction). The UNIQUE constraint
-- is what actually makes ON CONFLICT DO NOTHING deduplicate.
-- ---------------------------------------------------------------------
CREATE TABLE perfume_notes (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    perfume_id    BIGINT      NOT NULL REFERENCES perfumes(id)    ON DELETE CASCADE,
    ingredient_id BIGINT      NOT NULL REFERENCES ingredients(id) ON DELETE CASCADE,
    layer         VARCHAR(20) NOT NULL,   -- 'top' | 'heart' | 'base'
    UNIQUE (perfume_id, ingredient_id, layer)
);

-- ---------------------------------------------------------------------
-- perfume_accords : main accords ranked by dominance (rank 1 = strongest).
-- 'rank' is the real signal from the data; no fabricated percentage.
-- ---------------------------------------------------------------------
CREATE TABLE perfume_accords (
    id         BIGINT   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    perfume_id BIGINT   NOT NULL REFERENCES perfumes(id) ON DELETE CASCADE,
    accord_id  BIGINT   NOT NULL REFERENCES accords(id)  ON DELETE CASCADE,
    rank       SMALLINT NOT NULL,
    UNIQUE (perfume_id, accord_id)
);

-- ---------------------------------------------------------------------
-- Indexes for the id-based search paths
-- ---------------------------------------------------------------------
CREATE INDEX idx_perfume_notes_ingredient ON perfume_notes(ingredient_id);
CREATE INDEX idx_perfume_accords_accord   ON perfume_accords(accord_id);
CREATE INDEX idx_perfumes_brand           ON perfumes(brand_id);

-- Trigram indexes for the text search (name search box), also used by
-- the ingredient-duplicate-candidate query mentioned separately.
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE INDEX idx_perfumes_title_trgm    ON perfumes    USING gin (title gin_trgm_ops);
CREATE INDEX idx_ingredients_name_trgm  ON ingredients USING gin (name  gin_trgm_ops);

COMMIT;